
# Generated by Qodo Gen
from AdvancedModeling import phase_plot_data
import pytest

class TestPhasePlotData:

    # Function correctly converts a dataframe column to a list of phase-shifted sublists
    def test_converts_dataframe_to_phase_shifted_sublists(self):
        # Arrange
        import pandas as pd
        import numpy as np
    
        # Create a test dataframe with a single column
        test_data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        df = pd.Series(test_data)
        phases = 3
    
        # Act
        result = phase_plot_data(df, phases)
    
        # Assert
        assert len(result) == phases
        assert result[0] == [1, 2, 3, 4, 5, 6, 7, 8]
        assert result[1] == [2, 3, 4, 5, 6, 7, 8, 9]
        assert result[2] == [3, 4, 5, 6, 7, 8, 9, 10]

    # Function returns None when phases parameter is not an integer
    def test_returns_none_when_phases_not_integer(self):
        # Arrange
        import pandas as pd
    
        # Create a test dataframe
        test_data = [1, 2, 3, 4, 5]
        df = pd.Series(test_data)
        invalid_phases = 2.5  # Float instead of integer
    
        # Act
        result = phase_plot_data(df, invalid_phases)
    
        # Assert
        assert result is None